Configurable border radius
userXinos/image-tools pull request #12
Opened 2021-05-05 18:18 UTC by Encode42

Lets the user change the border radius. I took inspiration from the square lens feature of the BetterDiscord equivalent of this plugin.

I don't know any Russian so I translated the setting via [DeepL](https://deepl.com/translate), if there's anything wrong with the translation feel free to comment!

**Default Radius:**
![](https://media.discordapp.net/attachments/365455566329348097/839566208780075019/2021-05-05_14.15.51.png)

**50% Radius:**
![](https://media.discordapp.net/attachments/365455566329348097/839566209292435527/2021-05-05_14.16.09.png)

**0% Radius:**
![](https://media.discordapp.net/attachments/365455566329348097/839566208991100948/2021-05-05_14.16.00.png)

2021-05-06 05:16 UTC, userXinos commented
I do not know in what cases this is generally needed, but let it be

2021-05-06 05:20 UTC, userXinos requested changes
NOTE will be superfluous?

2021-05-07 02:30 UTC, userXinos approved these changes

2021-06-03 01:54 UTC, Encode42 commented
I've lost motivation on this pull request, as you can tell by the lack of progress. In my opinion it's ready for merge once the redundant language line is removed and the code is rebased on the latest commits on the repo.

2021-06-03 02:02 UTC, userXinos commented
I will update the code according to the changes, I am waiting for the fix i18n from accidentally canceled by review

2021-06-03 02:23 UTC, userXinos requested changes
`NOTE` will be superfluous?

2021-07-15 03:39 UTC, Encode42 commented
I've merged upstream and resolved the unnecessary language string.

2021-07-16 04:01 UTC, userXinos approved these changes

2021-07-16 04:10 UTC, merged

2021-07-16 04:14 UTC, userXinos commented
Very cool.
I just made the style more reactive so that you don't have to close the modal to see the changes